import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
blur = true
opacity = 0.8
option_as_alt = "Both"
startup_mode="FullScreen"

[font]
normal.family = "VictorMono Nerd Font Mono"
size = 19
