source ~/dev/config/editor/plugins.vim                
source ~/dev/config/editor/settings.vim
source ~/dev/config/editor/pluginsconf/coc-config.vim 
source ~/dev/config/editor/pluginsconf/nerdetree.vim
source ~/dev/config/editor/pluginsconf/vim-fugitive.vim
source ~/dev/config/editor/pluginsconf/golps.vim
source ~/dev/config/editor/pluginsconf/vim-prettier.vim
source ~/dev/config/editor/pluginsconf/file-context.vim
source ~/dev/config/editor/pluginsconf/nerd-commentor.vim
source ~/dev/config/editor/pluginsconf/rust.vim
source ~/dev/config/editor/pluginsconf/telescope.vim
source ~/dev/config/editor/pluginsconf/luaSnip.vim
