require("settings")
require("mappings")
require("packer-config")
require("nvim-tree-config")
-- require("lsp-config.language-servers")
require("lsp-config.nvim-cmp")
require("lualine-config")
require("barbar-config")
